name: predicate
main: com.mineclay.predicate.PredicatePlugin
version: ${version}
author: i@thetd.me
depend:
  - groovyrt
commands:
  predicate:
    permission: predicate
    usage: /<command> <player> <conditions> then <command-to-execute>
    description: "/predicate theTd 'normal'=='normal' && matchset('event') then cpdc add event kill 1"
